-- Delete existing crops to avoid duplicates
DELETE FROM public.crops_master;

-- Insert all crops listed by the user
INSERT INTO public.crops_master (name, category) VALUES
('Wheat', 'Cereal'),
('Rice', 'Cereal'),
('Maize', 'Cereal'),
('Barley', 'Cereal'),
('Bajra', 'Millet'),
('Jowar', 'Millet'),
('Ragi', 'Millet'),
('Sorghum', 'Millet'),
('Foxtail millet', 'Millet'),
('Pearl millet', 'Millet'),
('Kodo millet', 'Millet'),
('Little millet', 'Millet'),
('Barnyard millet', 'Millet'),
('Finger millet', 'Millet'),
('Black gram', 'Pulse'),
('Green gram', 'Pulse'),
('Red gram', 'Pulse'),
('Chickpeas', 'Pulse'),
('Horse gram', 'Pulse'),
('Lentils', 'Pulse'),
('Cowpeas', 'Pulse'),
('Soybean', 'Oilseed'),
('Peas', 'Pulse'),
('Mustard', 'Oilseed'),
('Groundnut', 'Oilseed'),
('Sesame', 'Oilseed'),
('Sunflower', 'Oilseed'),
('Safflower', 'Oilseed'),
('Linseed', 'Oilseed'),
('Cotton', 'Fiber'),
('Sugarcane', 'Sugar'),
('Jute', 'Fiber'),
('Tobacco', 'Commercial'),
('Tea', 'Commercial'),
('Coffee', 'Commercial'),
('Coconut', 'Plantation'),
('Areca nut', 'Plantation'),
('Cashew', 'Plantation'),
('Cardamom', 'Spice'),
('Turmeric', 'Spice'),
('Ginger', 'Spice'),
('Garlic', 'Spice'),
('Onion', 'Vegetable'),
('Tomato', 'Vegetable'),
('Potato', 'Vegetable'),
('Brinjal', 'Vegetable'),
('Okra', 'Vegetable'),
('Cabbage', 'Vegetable'),
('Cauliflower', 'Vegetable'),
('Carrot', 'Vegetable'),
('Radish', 'Vegetable'),
('Spinach', 'Vegetable'),
('Coriander', 'Herb'),
('Fenugreek', 'Herb'),
('Lettuce', 'Vegetable'),
('Chilli', 'Spice'),
('Bell pepper', 'Vegetable'),
('Pumpkin', 'Vegetable'),
('Bitter gourd', 'Vegetable'),
('Bottle gourd', 'Vegetable'),
('Ridge gourd', 'Vegetable'),
('Ash gourd', 'Vegetable'),
('Watermelon', 'Fruit'),
('Musk melon', 'Fruit'),
('Papaya', 'Fruit'),
('Banana', 'Fruit'),
('Mango', 'Fruit'),
('Guava', 'Fruit'),
('Pomegranate', 'Fruit'),
('Orange', 'Fruit'),
('Lemon', 'Fruit'),
('Sweet lime', 'Fruit'),
('Sapota', 'Fruit'),
('Apple', 'Fruit'),
('Pear', 'Fruit'),
('Litchi', 'Fruit'),
('Grapes', 'Fruit'),
('Pineapple', 'Fruit'),
('Jackfruit', 'Fruit'),
('Amla', 'Fruit'),
('Custard apple', 'Fruit'),
('Fig', 'Fruit'),
('Dragon fruit', 'Fruit'),
('Avocado', 'Fruit'),
('Strawberry', 'Fruit'),
('Kiwi', 'Fruit'),
('Passion fruit', 'Fruit'),
('Beetroot', 'Vegetable'),
('Turnip', 'Vegetable'),
('Zucchini', 'Vegetable'),
('Broccoli', 'Vegetable'),
('Kale', 'Vegetable'),
('Methi', 'Herb'),
('Mint', 'Herb'),
('Basil', 'Herb'),
('Curry leaves', 'Herb'),
('Drumstick', 'Vegetable'),
('Taro root', 'Vegetable'),
('Yam', 'Vegetable'),
('Sweet potato', 'Vegetable'),
('Sugar beet', 'Sugar');