// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijwlsmtlhzelzeieghpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlqd2xzbXRsaHplbHplaWVnaHBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2OTQ0NTMsImV4cCI6MjA2NTI3MDQ1M30.Debd_koxv1KM2-bhs_qb0uRc2f68zXv_wCBjxgOPgKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);